### ISSUE TITLE
timestamp in build prevents reproducible builds

### ISSUE THREAD

**Issue by karlp** [pagekite/libpagekite#12]
https://wiki.debian.org/ReproducibleBuilds/Howto#Files_in_data.tar_contain_timestamps

**Comment by pagekite** [comment]
I know it's late, but do you happen to remember where the timestamps were appearing? `Make version` does this quite deliberately, but it's part of my release workflow, not something anyone else should really be running.

**Comment by pagekite** [comment]
I'm closing this; I am unaware of any timestamps in the builds, except for the date which I insert into the version number when I'm doing something release-ish. This should not be done by packagers.

Grepping for the __DATE__ and __TIME__ macros doesn't show anything (including a grep of the libev source).

Please feel free to reopen or file a new issue if I'm missing something here!
