### ISSUE TITLE
create a new pagekite domain using libpagekite?

### ISSUE THREAD

**Issue by cbrake** [pagekite/libpagekite#14]
Hi,

Just got libpagekite working -- great stuff!  Is it possible to create a new x.y.pagekite.me sub domain from the libpagekite API?  Or do I need to create x.y.pagekite.me in the pagekit.net web interface before I can connect to it from libpagekite?

Thanks,
Cliff

**Comment by BjarniRunar** [comment]
Currently libpagekite can only connect to existing kites, it has no logic for registration (and sorry about the super-late reply).

**Comment by pagekite** [comment]
Closing this; although libpagekite might gain support for the pagekite.net XML-RPC API at some point, it is by no means a given that that is actually a good idea. I am currently leaning towards "no"; it seems libpagekite would have little to add over using a generic xmlrpc library.
