### ISSUE TITLE
configure script is not cross-compilation friendly

### ISSUE THREAD

**Issue by guillerodriguez** [pagekite/libpagekite#16]
The configure script fails while checking for jni.h when cross-compiling.
Looks like this is caused by ax_jni_include_dir.m4 using AC_CHECK_FILE, [which dies when cross-compiling](http://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Files.html).

**Comment by pagekite** [comment]
I think you fixed this. :)  Feel free to reopen if not.
