### ISSUE TITLE
"stack smashing detected" crash in pk_log_raw_data

### ISSUE THREAD

**Issue by fabricedesre** [pagekite/libpagekite#29]
Seen with a log level of PK_LOG_ALL:

#0  0x00007fea6df62428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fea6df6402a in __GI_abort () at abort.c:89
#2  0x00007fea6dfa47ea in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fea6e0bb8a2 "*** %s ***: %s terminated\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007fea6e04556c in __GI___fortify_fail (msg=<optimized out>, msg@entry=0x7fea6e0bb884 "stack smashing detected") at fortify_fail.c:37
#4  0x00007fea6e045510 in __stack_chk_fail () at stack_chk_fail.c:28
#5  0x00007fea6e304f91 in pk_log_raw_data (level=level@entry=524288, prefix=prefix@entry=0x7fea6e309ab7 "W", data=data@entry=0x7fea6e72b299, bytes=bytes@entry=48) at pklogging.c:124
#6  0x00007fea6e2ff649 in pkc_raw_write (pkc=pkc@entry=0x7fea6e7164c0, data=data@entry=0x7fea6e72b299 "\026\003\001\002", length=length@entry=517) at pkconn.c:362
#7  0x00007fea6e2ffa24 in pkc_write (pkc=pkc@entry=0x7fea6e7164c0, data=0x7fea6e72b299 "\026\003\001\002", length=517) at pkconn.c:479
#8  0x00007fea6e303f03 in pkm_chunk_cb (fe=0x7fea6e705790, chunk=0x7fea6e72af40) at pkmanager.c:234
#9  0x00007fea6e2fd709 in pk_parser_parse_new_data (parser=parser@entry=0x7fea6e72af20, length=length@entry=670) at pkproto.c:299
#10 0x00007fea6e2fd910 in pk_parser_parse (parser=0x7fea6e72af20, length=670, 
    data=data@entry=0x7fea6e705824 "299\r\nSID: 313\r\nProto: https\r\nHost: remote.3d1be7d141b76e117b84c154f309a9381864be00.box.knilxof.org\r\nPort: 443\r\nRIP: ::ffff:71.198.7.190\r\nRPort: 48006\r\n\r\n\026\003\001\002") at pkproto.c:346
#11 0x00007fea6e302d4b in pkm_tunnel_readable_cb (loop=<optimized out>, w=<optimized out>, revents=<optimized out>) at pkmanager.c:613
#12 0x00007fea6dd22d73 in ev_invoke_pending () from /usr/lib/x86_64-linux-gnu/libev.so.4
#13 0x00007fea6dd263de in ev_run () from /usr/lib/x86_64-linux-gnu/libev.so.4
#14 0x00007fea6e301885 in ev_loop (flags=0, loop=<optimized out>) at /usr/include/ev.h:835
#15 pkm_run (void_pkm=0x7fea6e703010) at pkmanager.c:1673
#16 0x00007fea6d45c70a in start_thread (arg=0x7fea6c710700) at pthread_create.c:333
#17 0x00007fea6e03382d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by guillerodriguez** [comment]
@fabricedesre I think this may have been fixed by pull request #34.

**Comment by pagekite** [comment]
Thank you for reporting this, and thanks for the fix!

**Comment by fabricedesre** [comment]
Indeed, fixed by #34
