### ISSUE TITLE
Make configure.ac cross-compiler friendly

### ISSUE THREAD

**Issue by fabricedesre** [pagekite/libpagekite#30]
Cross compiling to an armhf target failed because the linker could not find rpl_malloc. This is due to some autotools "magic".

Feel free to cherry pick the fix on my fork here:
https://github.com/fabricedesre/libpagekite/commit/219fdee75de657df64bfe4674d38828741721c41

**Comment by karlp** [comment]
wat? what toolchain were you using?  I'm an autotools hater, but seriously? manually specifying malloc?

**Comment by fabricedesre** [comment]
Just used the armhf arch on ubuntu.

**Comment by guillerodriguez** [comment]
I have not tried armhf but I can build for armle without problems (except for issue #27). Just in case this info is useful.

**Comment by pagekite** [comment]
@fabricedesre Could you comment on whether you feel this is still necessary? The fix you've linked to doesn't really feel right to me.

**Comment by fabricedesre** [comment]
I don't like the change either, but as I said previously, this looks like a necessary evil to build on armhf (I'm targetting the RPi2). I'd love to not have to fork...

**Comment by BjarniRunar** [comment]
Fair enough.

Although a bit silly, it does look like a totally harmless change. I'm not even sure why we're checking for malloc at all, the code doesn't do anything with it. I probably just inherited that from whatever boilerplate evolved into our autoconf.

**Comment by guillerodriguez** [comment]
@pagekite I may be wrong but I think that it is not enough to add malloc to AC_CHECK_FUNCS; you also need to remove AC_FUNC_MALLOC (see the original patch from @fabricedesre, and also other similar cases such as [this](https://github.com/LLNL/ior/issues/4) and [this](https://github.com/obgm/libcoap/issues/31))
