### ISSUE TITLE
Abort due to negative fd being passed to libev

### ISSUE THREAD

**Issue by guillerodriguez** [pagekite/libpagekite#37]
I'm doing some stress testing to verify the fix for #31 and #35 and I am seeing pagekitec being terminated due to an assertion failure in libev. Apparently libpagekite is passing a negative fd to libev. Here are the last bits of the log output:

```
[...]
t=2017-02-22 17:40:58.735; ts=58adcd2a; tid=b4b3fb70; ll=122b; msg=Connecting to [54.173.41.120]:443 (session=new)
t=2017-02-22 17:41:03.499; ts=58adcd2f; tid=b733fb70; ll=122c; msg=Tick!  [repeating=yes, next=21, v=0.91.161104C]
t=2017-02-22 17:41:24.503; ts=58adcd44; tid=b733fb70; ll=122d; msg=Tick!  [repeating=yes, next=16, v=0.91.161104C]
t=2017-02-22 17:41:40.506; ts=58adcd54; tid=b733fb70; ll=122e; msg=Tick!  [repeating=yes, next=16, v=0.91.161104C]
t=2017-02-22 17:41:56.509; ts=58adcd64; tid=b733fb70; ll=122f; msg=Tick!  [repeating=yes, next=16, v=0.91.161104C]
t=2017-02-22 17:42:12.513; ts=58adcd74; tid=b733fb70; ll=1230; msg=Tick!  [repeating=yes, next=16, v=0.91.161104C]
t=2017-02-22 17:42:28.516; ts=58adcd84; tid=b733fb70; ll=1231; msg=Tick!  [repeating=yes, next=16, v=0.91.161104C]
t=2017-02-22 17:42:28.516; ts=58adcd84; tid=b4b3fb70; ll=1232; msg=6: TLS handshake failed!
t=2017-02-22 17:42:28.517; ts=58adcd84; tid=b4b3fb70; ll=1233; msg=6: Connected!
t=2017-02-22 17:42:28.517; ts=58adcd84; tid=b733fb70; ll=1234; msg=6: Disconnected, closing.
pagekitec: ev.c:3836: ev_io_start: Assertion `("libev: ev_io_start called with negative fd", fd >= 0)' failed.
Aborted

```

**Comment by BjarniRunar** [comment]
Hmm. Could this be triggered by you setting sockfd = -1 in one of the recent patches, and that falling through?

**Comment by guillerodriguez** [comment]
Assuming your comment in [pkmanager.c, line 323](https://github.com/guillerodriguez/libpagekite/blob/192900234b0a611287c876d6b4236dd0ba711b05/libpagekite/pkmanager.c#L323) is correct, then I don't see how that would happen: Either addr == null, then the function returns without using sockfd anywhere, or if addr != null, sockfd will be updated with the value returned by `PKS_socket` (then the initial value does not make any difference).

On the other hand if your comment in line 323 is incorrect and you can actually have errno = EINPROGRESS there, then the original code was wrong as well (it was setting sockfd = 0 before my change, which would have fallen through as well).

Also see the last lines in the traces I posted. This strange sequence of "TLS handshake failed!" immediately followed by "Connected!" and then "Disconnected" (see timestamps) for fd 6 look suspicious.

**Comment by BjarniRunar** [comment]
I've looked at this in more detail - you are absolutely right, there are funky things going on.

As you suggested in your e-mail (off github), there is a race condition; the code does bad things if a connection attempt takes longer than one housekeeping interval, as illustrated in the log snippet above. Basically, one thread can be busy trying to make a connection while the main event loop decides to tidy up and reset the underlying data structures.

I'm working on this a bit at my end.

**Comment by guillerodriguez** [comment]
The latest commits seem to have taken care of this case, and also of the others we discussed which ended up in SIGSEGVs instead of aborts(), but which were probably caused by the same underlying problem.

We've been running tests in our hardened environment for more than 2 days and have not seen this happening again. So I am closing the issue.
