### ISSUE TITLE
Use CLOCK_MONOTONIC for deadlines

### ISSUE THREAD

**Issue by BjarniRunar** [pagekite/libpagekite#45]
From e-mail (lightly edited):

> I just came across this:
> 
> https://github.com/pagekite/libpagekite/commit/a2f26f60ab26ac06e21f92c5a192915e2287fcb1
> 
> I had not realized you were actually using CLOCK_REALTIME (and
> now gettimeofday) for waiting for a timeout. This is
> problematic if the system time can change (via NTP or because
> of the user manually adjusts the time/date).
> 
> I would like to suggest to use clock_gettime with
> CLOCK_MONOTONIC for this purpose, if available. If
> clock_gettime and CLOCK_MONOTONIC are not available, then you
> can fall back to gettimeofday (but this has problems).
> 
> Here's some additional background:
> 
> https://bugs.python.org/issue23428
> https://blog.habets.se/2010/09/gettimeofday-should-never-be-used-to-measure-time.html
> https://stackoverflow.com/questions/14248033/clock-monotonic-and-pthread-mutex-timedlock-pthread-cond-timedwait

**Comment by pagekite** [comment]
This should be fixed now, at least in cases where CLOCK_MONOTONIC is available.
