### ISSUE TITLE
Crash in function pk_parse_kite_request on 32 bit host (CortexA9 and i386 tested)

### ISSUE THREAD

**Issue by RomTok** [pagekite/libpagekite#64]
When I try to connect  with my own front-end, pagekitec crashes in function pk_parse_kite_request.
This happens only on 32 bit systems.
My command line: ./pagekitec -v -v -v -v -S -I 1111 http N.N.N.N 2222 12345

In my opinion, the error in this line is pkproto.c # L711:
```
  int llen = strlen(line);
  copy = malloc(llen+1);
  strcpy(copy, line);

  char* end = copy + llen + 1;
 *end = '\0';
```
An extra '\0' is written to the area outside the allocated memory.
When I remove the "+1", everything works as expected.
Sorry for my english :)

**Comment by BjarniRunar** [comment]
Thank you for the detailed report! I'll take a look at this soon.
