### ISSUE TITLE
possibile to use on a esp8266 chip ?

### ISSUE THREAD

**Issue by deedos** [pagekite/libpagekite#68]
Hi. I have been using pagekite.py with a raspberry pi and loves it. I Came across this lib and I wonder if I could use  in a esp8266 firmware ? My project uses this firmware https://github.com/thorrak/brewpi-esp8266 
thanks in advance

**Comment by BjarniRunar** [comment]
I don't know! You tell me. :-)  If that platform has libev and POSIX networking, then it's likely.

**Comment by BjarniRunar** [comment]
Having taken a look at https://en.wikipedia.org/wiki/ESP8266 , I think it's safe to assume this hardware is too small to run libpagekite.

In particular we depend on both pthreads and POSIX networking APIs, neither of which I would expect are available on this type of device. And I definitely don't expect to see people doing full TLS on a device like this, which means any implementation would be too insecure for me to recommend it for anything non-trivial.

If someone knows better and would like to take this on, we can reopen this issue, but for now I think leaving this open would be misleading.
