### ISSUE TITLE
pagekitec: expand status file information

### ISSUE THREAD

**Issue by karlp** [pagekite/libpagekite#73]
In order to better evaluate the ```pagekitec_update_ts``` field in the status message files, it would be helpful to have the ```#define STATUS_MIN_INTERVAL 240``` value included.

Also, when the process exits, it would be nice if it could either a) remove the file, or b) write a "shutdown" state or similar, to avoid having to go and check the pid manually all the time.

**Comment by karlp** [comment]
adding a shutdown state requires adding to the ```pk_status_t``` enum however...

**Comment by karlp** [comment]
Extended: The log will report, "DDNS: Update failed for xxx. 
msg=DDNS: Update failed for blah.fqdn (http://dnsup.whitelabel.fqdn/?hostname=params -> badauth)"  but the status file status is "pagekitec_status": "no_network"

Would be "nice" to have more/better states?

**Comment by BjarniRunar** [comment]
I've addressed the concrete requests here; there is now a shutdown state and the interval is reported. The no_network weirdness is being discussed over in #74 - I think it is fixed too now.

Regarding the more vague "need moar states"... maybe? The states are a rough summary, to figure out what is really going on, the log file is the place to look. Both "problem" and "flying" could be broken down a bit more (what kind of problem? have we actually seen user traffic yet?) but I don't have clear ideas yet on implementations.

**Comment by karlp** [comment]
This is a very solid improvement, thanks.  (I later moved to actually checking the process with the pid from the file had pagekite in the name, so ... I'm not actually using the age check in the file right now anyway, but it's still useful)
